require("config.options")
require("config.keymaps")
require("config.plugins")
require("config.commands")
require("config.lsp")
require("config.theme")
require("config.telescope")
require("config.pluginsConfig")
